site_name: Medhir
site_url: https://medhir.in

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: blue gray
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - toc.integrate

nav:
  - Home: index.md
  - Project Overview: project-overview.md
  - Frontend: 
      - Pages-Components: frontend/pages-components.md
  - Integration:
      - Integration: integration/integration.md
  - Backend:
      - Spring Boot Setup: backend/spring-boot.md
      - MongoDB Schema: backend/database.md
      - Google Sheet Attendance Sync: backend/google-attendance-sync.md
  - Deployment:
      - Podman & Containerization: deployment/podman.md
  - API Documentation: api/index.md
  - FAQ: faq.md

